### ISSUE TITLE
eth-keys have been upgraded

### ISSUE THREAD

**Issue by umrashrf** [ethereum/eth-keyfile#15]
* Version: 3.6.5
* Python: 3.6
* OS: linux

### What was wrong?
dependency issue

Please include any of the following that are applicable:

* The code which produced the error
pipenv install -r requirements.txt

* The full output of the error

### How can it be fixed?
The package eth-account depends on eth-keyfile [required: >=0.5.0,<0.6.0, installed: 0.5.1] and eth-keys [required: >=0.2.0b3,<0.3.0, installed: 0.2.0b3] but eth-keyfile depends on eth-keys [required: >=0.1.0-beta.4,<1.0.0, installed: 0.2.0b3].

Fill this section in if you know how this could or should be fixed.
Just change eth-keys in setup.py to a newer version. Ideally 0.2.0b3.

**Comment by umrashrf** [comment]
https://github.com/ethereum/eth-account/blob/master/setup.py#L50

**Comment by carver** [comment]
It looks like 0.2.0b3 is a valid version in both dependencies (`eth-keys` and `eth-account`), and is getting installed. Can you clarify the problem?

**Comment by umrashrf** [comment]
Yes ```pip``` does not complain but ```pipenv``` does complain. ```pipenv install --skip-lock``` will skip complaining.

After installing with ```pip```, you can use ```pipenv graph``` to see two eth-keys.

**Comment by carver** [comment]
After some back and forth with the `pipenv` team about what should be supported, we decided not to explicitly support `pipenv`. Only `pip` is guaranteed to work. Closing as not a priority, but feel free to continue the discussion here.
