### ISSUE TITLE
Extend keyfile to handle eth2.0 BLS keying material

### ISSUE THREAD

**Issue by ralexstokes** [ethereum/eth-keyfile#26]
In particular, implement this:

https://eips.ethereum.org/EIPS/eip-2335

**Comment by ralexstokes** [comment]
noting that the new EIP has a new version for the keyfile format, i.e. `v4`.

so this library should delegate to the appropriate routines based on the version of particular key file

**Comment by pipermerriam** [comment]
Probably something we could bounty...
