### ISSUE TITLE
Question about Scrypt Default Parameter

### ISSUE THREAD

**Issue by darwintree** [ethereum/eth-keyfile#39]
### What was wrong?

Currently, when using `scrypt` as kdf, as shown in https://github.com/ethereum/eth-keyfile/blob/master/eth_keyfile/keyfile.py#L87

```
SCRYPT_R = 1
SCRYPT_P = 8
```

are used as default parameter. But is it a typo as here is the suggestion from [pycryptodome](https://github.com/Legrandin/pycryptodome/blob/master/lib/Crypto/Protocol/KDF.py#L364)

```
    A good choice of parameters *(N, r , p)* was suggested
    by Colin Percival in his `presentation in 2009`__:
    - *( 2¹⁴, 8, 1 )* for interactive logins (≤100ms)
    - *( 2²⁰, 8, 1 )* for file encryption (≤5s)
```

### How can it be fixed?

Change 

```
SCRYPT_R = 1
SCRYPT_P = 8
```

to

```
SCRYPT_R = 8
SCRYPT_P = 1
```

**Comment by usd-yamazaki** [comment]
`Error: Scrypt: N must be larger than 1, a power of 2, less than 2^(128 * r / 8) and less than 2^32`

Currently, due to this issue, keys encrypted with web3py cannot be decrypted with ethersjs.
I'm in trouble...
